

notifications:
  email:
    recipients:
      - humberto.a.sanchez.ii@gmail.com
    on_success: change # default: change
    on_failure: always # default: always

language: python

dist: jammy

cache: pip

services:
  - xvfb

python:
  - "3.12"

install:
  - sudo apt update
  - sudo apt install libnotify-dev
  - sudo apt install libgtk-3-dev
  - sudo apt-get install -y  libsdl2-dev
  - GLOBAL=`python --version`
  - echo $GLOBAL
  - PY_VERSION=${GLOBAL#* }
  - pyenv global ${PY_VERSION}
  - pip install --upgrade pip
  - pip install wheel
  - pip install setuptools
  - pip install html-testRunner~=1.2.1
  - pip install six==1.16.0
  - pip install attrdict3
  - pip install wxPython
  - pip install codeallybasic==1.9.0
  - pip install codeallyadvanced==1.3.3
  - pip install pyutmodelv2==2.2.3
  - pip install untangle==1.2.1
  - pip install ogl==3.6.5

# command to run tests
script:
  - pip install buildlackey
  - unittests -v loud
