
version: '2.1'

orbs:
  python: circleci/python@2.1.1

workflows:
  main:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/

jobs:
  build:
    docker:
      - image: cimg/python:3.11-browsers
    executor: python/default
    steps:
      - checkout
      - run:
          name: Install library dependencies
          command: |
            sudo apt update
            sudo apt install libnotify-dev
            sudo apt install libgtk-3-dev
            sudo apt-get install -y  libsdl2-dev
            pip install --upgrade pip
            pip install wheel
            pip install setuptools
            pip install six==1.16.0
            pip install html-testRunner~=1.2.1
            pip install attrdict3
            pip install -U -f https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-22.04  wxPython
            pip install codeallybasic==1.0.0
            pip install codeallyadvanced==1.0.0
            pip install pyutmodelv2==2.1.0
            pip install ogl==2.1.0
            pip install untangle==1.2.1
            pip install buildlackey==1.6.3
      - run:
            name: run tests
            command: | 
              unittests
