from typing import cast
from unittest import TestSuite
from unittest import main as unitTestMain

from untangle import Element
from untangle import parse

from tests.ProjectTestBase import ProjectTestBase

from ogl.sd.OglSDInstance import OglSDInstance
from ogl.sd.OglSDMessage import OglSDMessage

from untanglepyut.Types import OglSDInstances

from untanglepyut.Types import OglSDMessages
from untanglepyut.Types import UntangledOglActors
from untanglepyut.Types import UntangledOglLinks

from untanglepyut.XmlVersion import XmlVersion

from untanglepyut.UnTangleSequenceDiagram import UnTangleSequenceDiagram


V11_SEQUENCE_DIAGRAM_DOCUMENT: str = """
<PyutDocument type="SEQUENCE_DIAGRAM" title="SequenceDiagram" scrollPositionX="0" scrollPositionY="0" pixelsPerUnitX="20" pixelsPerUnitY="20">
    <OglSDInstance width="100" height="400" x="129" y="50">
        <PyutSDInstance id="1" instanceName="hasiiInstance" lifeLineLength="200" />
    </OglSDInstance>
    <OglSDInstance width="100" height="400" x="418" y="50">
        <PyutSDInstance id="2" instanceName="franInstance" lifeLineLength="200" />
    </OglSDInstance>
    <OglSDInstance width="100" height="400" x="803" y="50">
        <PyutSDInstance id="3" instanceName="OzzeeInstance" lifeLineLength="200" />
    </OglSDInstance>
    <OglSDMessage>
        <PyutSDMessage id="4" message="calls()" sourceTime="148" destinationTime="150" sourceId="1" destinationId="2" />
    </OglSDMessage>
    <OglSDMessage>
        <PyutSDMessage id="5" message="spanks()" sourceTime="201" destinationTime="194" sourceId="2" destinationId="3" />
    </OglSDMessage>
    <OglSDMessage>
        <PyutSDMessage id="6" message="bites()" sourceTime="328" destinationTime="338" sourceId="3" destinationId="2" />
    </OglSDMessage>
</PyutDocument>
"""

V11_SEQUENCE_DIAGRAM_WITH_ACTOR_LINKS: str = """

    <PyutDocument type="SEQUENCE_DIAGRAM" title="Seq Diagram" scrollPositionX="0" scrollPositionY="0" pixelsPerUnitX="20" pixelsPerUnitY="20">
        <OglLink sourceAnchorX="155" sourceAnchorY="225" destinationAnchorX="360" destinationAnchorY="250" spline="False">
            <LabelCenter x="0" y="0" />
            <LabelSource x="-102" y="-25" />
            <LabelDestination x="88" y="19" />
            <PyutLink name="" type="ASSOCIATION" cardinalitySource="" cardinalityDestination="" bidirectional="False" sourceId="3" destinationId="1" />
        </OglLink>
        <OglActor width="80" height="100" x="75" y="175">
            <PyutActor id="3" name="ActorName" fileName="" />
        </OglActor>
        <OglSDInstance width="100" height="400" x="360" y="50">
            <PyutSDInstance id="1" instanceName="Instance1" lifeLineLength="200" />
        </OglSDInstance>
        <OglSDInstance width="100" height="400" x="781" y="50">
            <PyutSDInstance id="2" instanceName="Instance2" lifeLineLength="200" />
        </OglSDInstance>
        <OglSDMessage>
            <PyutSDMessage id="3" message="testMessage()" sourceTime="149" destinationTime="150" sourceId="1" destinationId="2" />
        </OglSDMessage>
    </PyutDocument>

"""


class TestUnTangleSequenceDiagram(ProjectTestBase):
    """
    Auto generated by the one and only:
        Gato Malo - Humberto A. Sanchez II
        Generated:  05 September 2023
    """
    @classmethod
    def setUpClass(cls):
        super().setUpClass()

    def setUp(self):
        super().setUp()

    def tearDown(self):
        super().tearDown()

    def testSequenceDiagramWithActorLink(self):

        root:                    Element = parse(V11_SEQUENCE_DIAGRAM_WITH_ACTOR_LINKS)
        sequenceDiagramDocument: Element = root.PyutDocument

        unTangleSequenceDiagram: UnTangleSequenceDiagram = UnTangleSequenceDiagram(xmlVersion=XmlVersion.V11)

        unTangleSequenceDiagram.unTangle(pyutDocument=sequenceDiagramDocument)

        oglActors: UntangledOglActors = unTangleSequenceDiagram.oglActors
        oglLinks:  UntangledOglLinks  = unTangleSequenceDiagram.oglLinks

        self.assertEqual(1, len(oglActors), 'Oops not enough Uml Actors')
        self.assertEqual(1, len(oglLinks), 'Oops not enough association links')

    def testOglSdMessage(self):
        unTangleSequenceDiagram: UnTangleSequenceDiagram = self._untangleSequenceDiagramDocument()

        oglSDMessages: OglSDMessages = unTangleSequenceDiagram.oglSDMessages

        self.assertEqual(3, len(oglSDMessages), 'Invalid message count')

        oglSDMessage: OglSDMessage = oglSDMessages[6]

        self.assertEqual('bites()', oglSDMessage.pyutSDMessage.message, "Missing bites message")
        self.assertEqual(328, oglSDMessage.pyutSDMessage.sourceY,       "Missing bites message")
        self.assertEqual(338, oglSDMessage.pyutSDMessage.destinationY,  "Missing bites message")

    def testOglSdInstance(self):
        unTangleSequenceDiagram: UnTangleSequenceDiagram = self._untangleSequenceDiagramDocument()

        oglSDInstances: OglSDInstances = unTangleSequenceDiagram.oglSDInstances

        self.assertEqual(3, len(oglSDInstances), 'Invalid instance count')

        oglSDInstance: OglSDInstance = oglSDInstances[3]

        self.assertEqual('OzzeeInstance', oglSDInstance.pyutSDInstance.instanceName, 'Incorrect instance name')
        self.assertEqual(200, oglSDInstance.pyutSDInstance.instanceLifeLineLength,           '')

    def testOnlySingleLinksCreated(self):

        unTangleSequenceDiagram: UnTangleSequenceDiagram = self._untangleSequenceDiagramDocument()

        oglSDInstances: OglSDInstances = unTangleSequenceDiagram.oglSDInstances

        for sdInstance in oglSDInstances.values():
            oglSDInstance: OglSDInstance = cast(OglSDInstance, sdInstance)
            instanceName: str = oglSDInstance.pyutSDInstance.instanceName
            if instanceName == 'hasiiInstance':
                self.assertEqual(1, len(oglSDInstance.messages), f'`{instanceName}` Should have a single message')
            elif instanceName == 'franInstance':
                self.assertEqual(3, len(oglSDInstance.messages), f'`{instanceName}` Should have a single message')
            elif instanceName == 'OzzeeInstance':
                self.assertEqual(2, len(oglSDInstance.messages), f'`{instanceName}` Should have a single message')

    def _untangleSequenceDiagramDocument(self) -> UnTangleSequenceDiagram:

        root:            Element = parse(V11_SEQUENCE_DIAGRAM_DOCUMENT)
        useCaseDocument: Element = root.PyutDocument

        unTangleSequenceDiagram: UnTangleSequenceDiagram = UnTangleSequenceDiagram(xmlVersion=XmlVersion.V11)

        unTangleSequenceDiagram.unTangle(pyutDocument=useCaseDocument)

        return unTangleSequenceDiagram


def suite() -> TestSuite:
    """You need to change the name of the test class here also."""
    import unittest

    testSuite: TestSuite = TestSuite()

    testSuite.addTest(unittest.defaultTestLoader.loadTestsFromTestCase(testCaseClass=TestUnTangleSequenceDiagram))

    return testSuite


if __name__ == '__main__':
    unitTestMain()
