
from typing import cast

from unittest import TestSuite
from unittest import main as unitTestMain

from miniogl.AttachmentSide import AttachmentSide
from miniogl.SelectAnchorPoint import SelectAnchorPoint
from untangle import Element
from untangle import parse

from ogl.OglClass import OglClass
from ogl.OglInterface2 import OglInterface2

from untanglepyut.Types import LinkableOglObjects
from untanglepyut.Types import UntangledLinks
from untanglepyut.Types import UntangledOglClasses
from untanglepyut.Types import UntangledOglLinks

from untanglepyut.XmlVersion import XmlVersion

from untanglepyut.v11.UnTangleOglClasses import UnTangleOglClasses
from untanglepyut.v11.UnTangleOglLinks import UnTangleOglLinks

from tests.TestBase import TestBase

V11_OGL_INTERFACE2_DOCUMENT: str = """
<PyutDocument type="CLASS_DIAGRAM" title="Simple Interface Diagram" scrollPositionX="0" scrollPositionY="0" pixelsPerUnitX="20" pixelsPerUnitY="20">
    <OglClass width="150" height="75" x="100" y="75">
        <PyutClass id="1" name="Implementor" stereotype="noStereotype" filename="" description="" displayMethods="True" displayStereotype="True" displayFields="True" displayParameters="Unspecified"/>
    </OglClass>
    <OglInterface2 attachmentPoint="EAST" x="250" y="112">
        <PyutInterface id="2" name="IClassInterface" description="">
            <PyutMethod name="MethodWithParameters" visibility="PUBLIC" returnType="">
                <PyutParameter name="strParam"  type="str"  defaultValue=""/>
                <PyutParameter name="intParam"  type="int"  defaultValue="1"/>
                <PyutParameter name="floatParam" type="float" defaultValue="1.0"/>
                <SourceCode/>
            </PyutMethod>
            <Implementor implementingClassName="Implementor"/>
        </PyutInterface>
    </OglInterface2>
</PyutDocument>
"""


class TestUnTangleOglLinks(TestBase):
    """
    Auto generated by the one and only:
        Gato Malo - Humberto A. Sanchez II
        Generated:  05 September 2023
    """
    @classmethod
    def setUpClass(cls):
        super().setUpClass()

    def setUp(self):
        super().setUp()

    def tearDown(self):
        super().tearDown()

    def testUnTangleOglInterface2(self):
        root:               Element = parse(V11_OGL_INTERFACE2_DOCUMENT)
        interface2Document: Element = root.PyutDocument

        unTangleOglClass:    UnTangleOglClasses  = UnTangleOglClasses(xmlVersion=XmlVersion.V11)
        unTangledOglClasses: UntangledOglClasses = unTangleOglClass.unTangle(pyutDocument=interface2Document)

        linkableOglObjects: LinkableOglObjects = LinkableOglObjects({})
        for aClass in unTangledOglClasses:
            oglClass: OglClass = cast(OglClass, aClass)
            linkableOglObjects[oglClass.id] = oglClass

        unTangleInterface2Diagram: UnTangleOglLinks   = UnTangleOglLinks(xmlVersion=XmlVersion.V11)

        untangledOglLinks: UntangledOglLinks = unTangleInterface2Diagram.unTangle(pyutDocument=interface2Document, linkableOglObjects=linkableOglObjects)

        self.assertEqual(1, len(untangledOglLinks), '')

        oglInterface2: UntangledLinks = untangledOglLinks[0]

        destinationAnchor: SelectAnchorPoint = cast(SelectAnchorPoint, oglInterface2.destinationAnchor)

        x, y = destinationAnchor.GetPosition()
        self.assertEqual(250, x, '')
        self.assertEqual(112, y, '')

        self.assertEqual(AttachmentSide.EAST, destinationAnchor.attachmentPoint, '')


def suite() -> TestSuite:
    """You need to change the name of the test class here also."""
    import unittest

    testSuite: TestSuite = TestSuite()

    testSuite.addTest(unittest.defaultTestLoader.loadTestsFromTestCase(testCaseClass=TestUnTangleOglLinks))

    return testSuite


if __name__ == '__main__':
    unitTestMain()
